service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

package:
  include:
    - src/**

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          method: get
          path: hello
